config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :couriers
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/courier.rb
# frozen_string_literal: true

class Courier < ApplicationRecord
  # after_create_commit -> do
  #   broadcast_prepend_to "courier_list", partial: "couriers/courier", locals: { courier: self }, target: "couriers"
  # end
  # or shorter equivalent:
  after_create_commit -> { broadcast_prepend_to "courier_list" }
  after_update_commit -> { broadcast_replace_to "courier_list" }
  after_destroy_commit -> { broadcast_remove_to "courier_list" }
  # cant be shorten to:
  # broadcasts_to ->(courier) { "courier_list" }, inserts_by: :prepend

  STATUSES = ["active", "blocked"].freeze

  validates :phone, presence: true
  validates :first_name, presence: true
  validates :status, presence: true, inclusion: { in: STATUSES }
  validates :phone, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

class CouriersController < ApplicationController
  before_action :set_courier, only: %i[show edit update destroy]

  # GET /couriers
  def index
    @couriers = Courier.all.order(updated_at: :desc)
  end

  # GET /couriers/1
  def show; end

  # GET /couriers/new
  def new
    @courier = Courier.new
  end

  # GET /couriers/1/edit
  def edit; end

  # POST /couriers
  def create
    @courier = Courier.new(courier_params)

    respond_to do |format|
      if @courier.save
        format.html { redirect_to courier_url(@courier), notice: "Courier was successfully created." }
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couriers/1
  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to courier_url(@courier), notice: "Courier was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couriers/1
  def destroy
    @courier.destroy

    respond_to do |format|
      format.html { redirect_to couriers_url, notice: "Courier was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:first_name, :last_name, :phone, :status)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/couriers_helper.rb
# frozen_string_literal: true

module CouriersHelper
end

app/views/couriers/_courier.html.erb
<div class="courier-list-item" id="<%= dom_id(courier, "wrapper") %>">
  <%= turbo_frame_tag dom_id(courier) do %>
      <p>
        <strong>First name:</strong>
        <%= courier.first_name %>
      </p>

      <p>
        <strong>Last name:</strong>
        <%= courier.last_name %>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= courier.phone %>
      </p>

      <p>
        <strong>Status:</strong>
        <%= courier.status %>
      </p>

      <%= link_to "Profile", courier, "data-turbo": false %> |
      <%= link_to "Edit", edit_courier_path(courier), "data-turbo-frame": dom_id(courier) %> |
      <%= button_to "Delete", courier, method: :delete, form_class: "inline-block" %>

  <% end %>
</div>

app/views/couriers/_form.html.erb
<%= form_with model: courier, data: { "turbo-frame": dom_id(courier) } do |form| %>
  <% if courier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(courier.errors.count, "error") %> prohibited this courier from being saved:</h2>

      <ul>
        <% courier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= link_to "Close via link", couriers_path, class: "block", data: { "turbo-frame": dom_id(courier) } %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/couriers/create.turbo_stream.erb
<%= turbo_stream.prepend "couriers" do %>
  <%= render partial: "couriers/courier", locals: { courier: @courier } %>
<% end %>

<%= turbo_stream.update Courier.new, "" %>

app/views/couriers/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@courier, "wrapper") %>

app/views/couriers/edit.html.erb
<h1>Editing courier</h1>

<%= turbo_frame_tag dom_id(@courier) do %>
  <%= render "form", courier: @courier %>

  <!-- <hr/>

  <div data-controller="hello-courier">
    <input data-hello-courier-target="name" type="text"></input>
    <button data-action="click->hello-courier#greet">Greet</button>
    <span>Hello courier!</span>
  </div>

  <div data-controller="clipboard">
    Courier PIN:
    <input type="text" value="1234" data-clipboard-target="source" readonly></input>
    <button data-action="clipboard#copy">Copy to Clipboard</button>
  </div> -->
<% end %>

app/views/couriers/index.html.erb
<%= turbo_stream_from "courier_list" %>

<p style="color: green"><%= notice %></p>

<h1 class="mb-10">Couriers</h1>

<%= turbo_frame_tag Courier.new %>

<div class="mb-10">
  <%= link_to "New courier", new_courier_path, data: { turbo_frame: dom_id(Courier.new) } %>
</div>

<div id="couriers">
  <% @couriers.each do |courier |%>
    <%= render courier %>
  <% end %>
</div>

app/views/couriers/new.html.erb
<h1>New courier</h1>

<%= turbo_frame_tag dom_id(@courier) do %>
  <%= render "form", courier: @courier %>
<% end %>

<br>

<div>
  <%= link_to "Back to couriers", couriers_path %>
</div>

app/views/couriers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_frame_tag dom_id(@courier) do %>
  <%= render @courier %>
<% end %>

<div>
  <%= link_to "Edit this courier", edit_courier_path(@courier) %> |
  <%= link_to "Back to couriers", couriers_path %>

  <%= button_to "Destroy this courier", @courier, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<% if flash.any? %>
  <div class="flash">
    <% flash.each do |flash_type, message| %>
      <div class="flash__message">
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<header class="global-footer">
  <span class="global-footer-text">Flash Courier App</span>
</header>

app/views/layouts/_header.html.erb
<header class="global-header">
  <span class="global-header-text">Flash Courier App</span>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flash Courier</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"> -->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <%= render "layouts/flash" %>

    <main class="main-block">
      <%= yield %>
    </main>
    <%= render partial: "layouts/footer" %>
  </body>
</html>